version: '3.8'

services:
  frontend:
    build: .
    container_name: vite-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
